### ISSUE TITLE
DRPolicy should not be editable post creation, to avoid changes to cluster sets or schedules

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#268]
Further, a policy change if allowed should reconcile all DRPCs that point to it. As policy (like StorageClass etc.) is a one time creation, we should add controls to ensure it is not editable post creation.

**Comment by vdeenadh** [comment]
Doesn't the user need the ability to change the DRPolicy post creation to change the replication schedule?

**Comment by ShyamsundarR** [comment]
The object is referenced by other objects, that have acted on the current data, like schedule and cluster set. If a different schedule is desired, then a new DRPolicy should be created, and the application should be DR disabled, and then reneabled against the new policy. (although we do not support disable at present, so that would need some thinking).

Currently, we do not take any action on policy changes (like schedule) and only impacts future reconciles of the DRPC referencing the policy if at all, hence disable changes to the policy, at least in the interim.

**Comment by hatfieldbrian** [comment]
# Problem
Making drpolicy immutable would solve a specific problem of cluster roles and cluster role bindings leaking.  Consider the following scenario:
1. a cluster is named in a drpolicy which results in a cluster role and cluster role binding being installed on it to permit vrg actions.
1. cluster name is removed from drpoilcy, but reconciler only sees current state of object and doesn't know that a cluster was removed, so its cluster roles and role bindings remain indefinitely but they should be removed.

Note: when a drpolicy is deleted a finalizer preserves the drpolicy object including names of clusters so that cluster roles and cluster role bindings can be removed from them.
# Solutions
If it is desirable to preserve drpolicy mutability, a drpolicy could instead be reconciled by:
1. querying all managed clusters and their associated namespaces for manifest works with a well-known name that are expected to contain cluster roles and cluster role bindings for vrg actions.
1. querying all drpolicies and generating a set of cluster names included in them.
1. removing or adding any cluster roles and cluster role bindings to match those that should exist for each cluster in the set.

Note: this solution removes the need for a finalizer.

Another solution is to preserve the previous state of a drpolicy within it somewhere to be able to identify changes.

**Comment by ShyamsundarR** [comment]
We need to address this via [webhooks](https://book.kubebuilder.io/reference/admission-webhook.html) for validation. Although k8s is moving towards [CustomResourceValidationExpressions](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2876-crd-validation-expression-language), the feature is still in beta, hence we would need to live with webhooks till this is GA, at which point we can add required validation expressions to the CRD itself for immutability. Also, current kubebuilder OpenAPI [markers](https://sdk.operatorframework.io/docs/building-operators/golang/references/openapi-validation/) do not have an immutability option (As of my reading/understanding)

The following `spec` fields should be immutable in the respective CRs:
DRCluster:
    - Region
    - s3ProfileName

DRPolicy:
    - SchedulingInterval
    - ReplicationClassSelector
    - VolumeSnapshotClassSelector
    - DRClusters
      - NOTE: If we disallow changing this, a dead cluster should be replaced with the same name, or the application should be DR disabled and reenabled using a new DRPolicy

DRPlacementControl:
    - PlacementRef
    - DRPolicyRef
    - PVCSelector

VolumeReplicationGroup:
    - PVCSelector
    - S3Profiles

This leaves the gap that an admin could update the ramen config map and edit the s3 location, which hence would require a reconcile of all resources to upload to the new s3 location. Determination of this is a bigger issue, and needs to be addressed separately (IOW we will not use webhooks for the same at present)

**Comment by ShyamsundarR** [comment]
Closed as referenced PR is merged.
