### ISSUE TITLE
e2e failure in reaching/fetching objects from github

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#397]
e2e scripts fail at times like so:
```
+ ocm_registration_operator_kubectl hub cluster-manager apply
+ kubectl --context hub apply -k 'https://github.com/stolostron/registration-operator/deploy/cluster-manager/config?ref=c723e190c454110797d89e67bcb33250b35e1fd7'
error: hit 27s timeout running '/usr/bin/git fetch --depth=1 origin c723e190c454110797d89e67bcb33250b35e1fd7'
```

The issue seems to be the timeout fetching the required resources from github. This may happen at any such fetch command in the scripts.

The problem auto resolves after some time, but adding an issue here for further investigation and information sharing.

**Comment by hatfieldbrian** [comment]
Also encountered with the foundation operator:
```sh
+ kubectl --context hub apply -k /tmp/bhatfiel/open-cluster-management/foundation/hub/hub
error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/stolostron/multicloud-operators-foundation/deploy/foundation/hub?ref=dc43ec703e62594e3942c7f06d38d1897550ffea': yaml: line 163: mapping values are not allowed in this context': hit 27s timeout running '/usr/bin/git fetch --depth=1 origin dc43ec703e62594e3942c7f06d38d1897550ffea'
```

I'm addressing this by specifying each manifest file url in the kustomization resources for registration and foundation operators, instead of the url of a directory containing a kustomization file.  Testing indicates it is faster and does not encounter the non-configurable 27-second timeout.
