### ISSUE TITLE
Investigate if using a string instead of a boolean for `Ramenconfig.VolSsync.Disable` is necessary

### ISSUE THREAD

**Issue by BenamarMk** [RamenDR/ramen#457]
According to [this comment](https://github.com/RamenDR/ramen/pull/434#discussion_r879405701), the suggestion is to change the boolean to a string, which might give us more options in the future.
This issue is to track that idea and investigate whether it is necessary.

**Comment by hatfieldbrian** [comment]
It seems volsync is enabled by default because the `disabled` boolean defaults to `false`.  I think volsync should be disabled by default, requiring the user opt-in to enable it.  API conventions suggest making optional fields without a built-in nil value pointers.  In this case, the volsync object could be made a pointer, which becomes the enabled/disabled indicator and eliminates the need for another one, namely the boolean.  If there is a need to add another string field for something, then that seems to be a separate issue, but I included my comment here nevertheless as it seems to be the right place for it.

**Comment by hatfieldbrian** [comment]
My earlier comment was meant to be in the context of the `vrg.spec.volsync.disabled` boolean

**Comment by raghavendra-talur** [comment]
This has been part of the API for quite some time now. Closing this issue. If needs arises, we will take a look at it later.
