### ISSUE TITLE
Improve project labels

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#598]
Some labels do not seem useful and we are missing some labels.

## Good

- [bug](https://github.com/RamenDR/ramen/labels/bug)
- [documentation](https://github.com/RamenDR/ramen/labels/documentation)
- [duplicate](https://github.com/RamenDR/ramen/labels/duplicate)
- [enhancement](https://github.com/RamenDR/ramen/labels/enhancement)
- [good first issue](https://github.com/RamenDR/ramen/labels/good%20first%20issue)
- [help wanted](https://github.com/RamenDR/ramen/labels/help%20wanted)
- [invalid](https://github.com/RamenDR/ramen/labels/invalid)
- [question](https://github.com/RamenDR/ramen/labels/question)
- [wontfix](https://github.com/RamenDR/ramen/labels/wontfix) 

## Remove

Better managed using milestones (assign milestone to issue)

- [current-sprint](https://github.com/RamenDR/ramen/labels/current-sprint)
- [next-sprint](https://github.com/RamenDR/ramen/labels/next-sprint)

## Remove? rename?

Priority tend to change, typically for every release you need to decide which issues are p1, p2, p3, then change priority based on actual progress.

Maybe rename to severity? usually does not change a lot and can help to plan the work.

- [priority-1](https://github.com/RamenDR/ramen/labels/priority-1)
  - 3 open from 2021, clearly these are not priority 1
- [priority-2](https://github.com/RamenDR/ramen/labels/priority-2)
  - 14 open from 2021 - are these really priority 2?
- [priority-3](https://github.com/RamenDR/ramen/labels/priority-3)

## Missing

- test - issue or bug related to test infrastructure or tests
- build - build related issues
- site - for issues like this one (not sure about the name)

**Comment by ShyamsundarR** [comment]
Removed added priority and sprint labels, these were used at a point but no longer.

I am always wary of creating sub-component labels (build, test, volsync, metro, etc.) as these require some level of constant maintenance. It would be better to get started with some form of triaging and then add labels to make better sense of the issues?

For now adding:
- build
- test
- project (instead of site, to denote project level operational issues)

We will assume everything else is related to some sub component till we get to triaging.

**Comment by nirs** [comment]
Look good now!
